### ISSUE TITLE
Installation process is unclear

### ISSUE THREAD

**Issue by vyrwu** [bence-toth/create-react-thing#52]
It is unclear whether the tool should be installed globally on within the existing npm registry.

It would be nice for CRT to be detecting and automatically choosing the project you are already using. Then, maybe it could let the user pick and choose different tools to be installed inside it, instead of always creating a fresh project with all the dependencies (sort of like a tool manager).

**Comment by bence-toth** [comment]
I'm not sure what you mean here. Can you please elaborate @vyrwu?

The library is intended to create a boilerplate for new projects, similar to Create React App. It is _not_ intended to be a tools manager for existing projects like the Vue UI.

As for the package, it does not need to be installed either as a dependency or as a global package. You can run it via `npx`, as it is recommended in the "Quick start" section of the readme. It would definitely work if you installed it globally, but I wouldn't recommend doing that because you would typically use it infrequently, so you would need to update the globally installed package to the new version before using it anyway.
